In [1]:
from nltk.corpus import stopwords #you can remove stop words for speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

In [2]:
file = open("1.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Climate change refers to long-term changes in the Earth's climate, including changes in temperature, precipitation, and wind patterns
Scientists have observed that human activities, such as burning fossil fuels and deforestation, are contributing to the rapid pace of climate change
The consequences of climate change include rising sea levels, more frequent and severe weather events, and disruptions to ecosystems and wildlife
Addressing climate change requires global cooperation and sustainable practices to reduce greenhouse gas emissions and mitigate its impacts.



In [3]:
print("Sentences are ", sentences)

Sentences are  [['Climate', 'change', 'refers', 'to', 'long-term', 'changes', 'in', 'the', "Earth's", 'climate,', 'including', 'changes', 'in', 'temperature,', 'precipitation,', 'and', 'wind', 'patterns'], ['Scientists', 'have', 'observed', 'that', 'human', 'activities,', 'such', 'as', 'burning', 'fossil', 'fuels', 'and', 'deforestation,', 'are', 'contributing', 'to', 'the', 'rapid', 'pace', 'of', 'climate', 'change'], ['The', 'consequences', 'of', 'climate', 'change', 'include', 'rising', 'sea', 'levels,', 'more', 'frequent', 'and', 'severe', 'weather', 'events,', 'and', 'disruptions', 'to', 'ecosystems', 'and', 'wildlife'], ['Addressing', 'climate', 'change', 'requires', 'global', 'cooperation', 'and', 'sustainable', 'practices', 'to', 'reduce', 'greenhouse', 'gas', 'emissions', 'and', 'mitigate', 'its', 'impacts.\n']]


In [4]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)


In [5]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.         0.22727273 0.28721348 0.23836565]
 [0.22727273 0.         0.32824398 0.23836565]
 [0.28721348 0.32824398 0.         0.38729833]
 [0.23836565 0.23836565 0.38729833 0.        ]]


In [6]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.2241068672792711, 1: 0.23457630024272336, 2: 0.2888184366837051, 3: 0.2524983957943003}


In [7]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.2888184366837051, ['The', 'consequences', 'of', 'climate', 'change', 'include', 'rising', 'sea', 'levels,', 'more', 'frequent', 'and', 'severe', 'weather', 'events,', 'and', 'disruptions', 'to', 'ecosystems', 'and', 'wildlife']), (0.2524983957943003, ['Addressing', 'climate', 'change', 'requires', 'global', 'cooperation', 'and', 'sustainable', 'practices', 'to', 'reduce', 'greenhouse', 'gas', 'emissions', 'and', 'mitigate', 'its', 'impacts.\n']), (0.23457630024272336, ['Scientists', 'have', 'observed', 'that', 'human', 'activities,', 'such', 'as', 'burning', 'fossil', 'fuels', 'and', 'deforestation,', 'are', 'contributing', 'to', 'the', 'rapid', 'pace', 'of', 'climate', 'change']), (0.2241068672792711, ['Climate', 'change', 'refers', 'to', 'long-term', 'changes', 'in', 'the', "Earth's", 'climate,', 'including', 'changes', 'in', 'temperature,', 'precipitation,', 'and', 'wind', 'patterns'])]


In [8]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  1


In [9]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 The consequences of climate change include rising sea levels, more frequent and severe weather events, and disruptions to ecosystems and wildlife


In [10]:
file = open("2.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

La historia del arte abarca una amplia gama de estilos, períodos y movimientos artísticos a lo largo de los siglos
Desde las pinturas rupestres prehistóricas hasta las obras maestras renacentistas y las expresiones contemporáneas, el arte ha reflejado la cultura, las creencias y las ideas de diversas sociedades
Los artistas han utilizado una variedad de técnicas y materiales para expresar su creatividad y transmitir mensajes emocionales, políticos y sociales a través de sus obras.



In [11]:
print("Sentences are ", sentences)

Sentences are  [['La', 'historia', 'del', 'arte', 'abarca', 'una', 'amplia', 'gama', 'de', 'estilos,', 'períodos', 'y', 'movimientos', 'artísticos', 'a', 'lo', 'largo', 'de', 'los', 'siglos'], ['Desde', 'las', 'pinturas', 'rupestres', 'prehistóricas', 'hasta', 'las', 'obras', 'maestras', 'renacentistas', 'y', 'las', 'expresiones', 'contemporáneas,', 'el', 'arte', 'ha', 'reflejado', 'la', 'cultura,', 'las', 'creencias', 'y', 'las', 'ideas', 'de', 'diversas', 'sociedades'], ['Los', 'artistas', 'han', 'utilizado', 'una', 'variedad', 'de', 'técnicas', 'y', 'materiales', 'para', 'expresar', 'su', 'creatividad', 'y', 'transmitir', 'mensajes', 'emocionales,', 'políticos', 'y', 'sociales', 'a', 'través', 'de', 'sus', 'obras.\n']]


In [12]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)


In [13]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.         0.18090681 0.36563621]
 [0.18090681 0.         0.1940285 ]
 [0.36563621 0.1940285  0.        ]]


In [14]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.36468906977342636, 1: 0.26247470720213906, 2: 0.37283622302443414}


In [15]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.37283622302443414, ['Los', 'artistas', 'han', 'utilizado', 'una', 'variedad', 'de', 'técnicas', 'y', 'materiales', 'para', 'expresar', 'su', 'creatividad', 'y', 'transmitir', 'mensajes', 'emocionales,', 'políticos', 'y', 'sociales', 'a', 'través', 'de', 'sus', 'obras.\n']), (0.36468906977342636, ['La', 'historia', 'del', 'arte', 'abarca', 'una', 'amplia', 'gama', 'de', 'estilos,', 'períodos', 'y', 'movimientos', 'artísticos', 'a', 'lo', 'largo', 'de', 'los', 'siglos']), (0.26247470720213906, ['Desde', 'las', 'pinturas', 'rupestres', 'prehistóricas', 'hasta', 'las', 'obras', 'maestras', 'renacentistas', 'y', 'las', 'expresiones', 'contemporáneas,', 'el', 'arte', 'ha', 'reflejado', 'la', 'cultura,', 'las', 'creencias', 'y', 'las', 'ideas', 'de', 'diversas', 'sociedades'])]


In [16]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  2


In [17]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Los artistas han utilizado una variedad de técnicas y materiales para expresar su creatividad y transmitir mensajes emocionales, políticos y sociales a través de sus obras.
. La historia del arte abarca una amplia gama de estilos, períodos y movimientos artísticos a lo largo de los siglos


In [18]:
file = open("3.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

La cuisine française est réputée dans le monde entier pour sa diversité, son raffinement et sa tradition culinaire
Des plats emblématiques tels que le coq au vin, le boeuf bourguignon et les macarons ont conquis les palais des gourmets du monde entier
Les chefs français sont célèbres pour leur créativité et leur utilisation experte des ingrédients locaux pour créer des plats délicieux et élégants qui incarnent l'art de la gastronomie.



In [19]:
print("Sentences are ", sentences)

Sentences are  [['La', 'cuisine', 'française', 'est', 'réputée', 'dans', 'le', 'monde', 'entier', 'pour', 'sa', 'diversité,', 'son', 'raffinement', 'et', 'sa', 'tradition', 'culinaire'], ['Des', 'plats', 'emblématiques', 'tels', 'que', 'le', 'coq', 'au', 'vin,', 'le', 'boeuf', 'bourguignon', 'et', 'les', 'macarons', 'ont', 'conquis', 'les', 'palais', 'des', 'gourmets', 'du', 'monde', 'entier'], ['Les', 'chefs', 'français', 'sont', 'célèbres', 'pour', 'leur', 'créativité', 'et', 'leur', 'utilisation', 'experte', 'des', 'ingrédients', 'locaux', 'pour', 'créer', 'des', 'plats', 'délicieux', 'et', 'élégants', 'qui', 'incarnent', "l'art", 'de', 'la', 'gastronomie.\n']]


In [20]:

def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)



In [21]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.         0.20412415 0.186339  ]
 [0.20412415 0.         0.27386128]
 [0.186339   0.27386128 0.        ]]


In [22]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.2982432051815699, 1: 0.3569434467208233, 2: 0.3448133480976067}


In [23]:
#Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.3569434467208233, ['Des', 'plats', 'emblématiques', 'tels', 'que', 'le', 'coq', 'au', 'vin,', 'le', 'boeuf', 'bourguignon', 'et', 'les', 'macarons', 'ont', 'conquis', 'les', 'palais', 'des', 'gourmets', 'du', 'monde', 'entier']), (0.3448133480976067, ['Les', 'chefs', 'français', 'sont', 'célèbres', 'pour', 'leur', 'créativité', 'et', 'leur', 'utilisation', 'experte', 'des', 'ingrédients', 'locaux', 'pour', 'créer', 'des', 'plats', 'délicieux', 'et', 'élégants', 'qui', 'incarnent', "l'art", 'de', 'la', 'gastronomie.\n']), (0.2982432051815699, ['La', 'cuisine', 'française', 'est', 'réputée', 'dans', 'le', 'monde', 'entier', 'pour', 'sa', 'diversité,', 'son', 'raffinement', 'et', 'sa', 'tradition', 'culinaire'])]


In [24]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  3


In [25]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Des plats emblématiques tels que le coq au vin, le boeuf bourguignon et les macarons ont conquis les palais des gourmets du monde entier. Les chefs français sont célèbres pour leur créativité et leur utilisation experte des ingrédients locaux pour créer des plats délicieux et élégants qui incarnent l'art de la gastronomie.
. La cuisine française est réputée dans le monde entier pour sa diversité, son raffinement et sa tradition culinaire


In [26]:
file = open("4.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))



print("Sentences are ", sentences)

Künstliche Intelligenz (KI) bezieht sich auf die Fähigkeit von Maschinen und Computern, Aufgaben auszuführen, die normalerweise menschliche Intelligenz erfordern
Dazu gehören das Lernen, das Problemlösen, die Spracherkennung und die Entscheidungsfindung
KI-Technologien wie maschinelles Lernen und neuronale Netze werden in verschiedenen Bereichen eingesetzt, von autonomen Fahrzeugen und Robotern bis hin zu personalisierten Empfehlungssystemen und medizinischer Diagnose.

Sentences are  [['Künstliche', 'Intelligenz', '(KI)', 'bezieht', 'sich', 'auf', 'die', 'Fähigkeit', 'von', 'Maschinen', 'und', 'Computern,', 'Aufgaben', 'auszuführen,', 'die', 'normalerweise', 'menschliche', 'Intelligenz', 'erfordern'], ['Dazu', 'gehören', 'das', 'Lernen,', 'das', 'Problemlösen,', 'die', 'Spracherkennung', 'und', 'die', 'Entscheidungsfindung'], ['KI-Technologien', 'wie', 'maschinelles', 'Lernen', 'und', 'neuronale', 'Netze', 'werden', 'in', 'verschiedenen', 'Bereichen', 'eingesetzt,', 'von', 'autonomen'

In [27]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

In [28]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)

Smilarity matrix 
 [[0.         0.26919095 0.14980118]
 [0.26919095 0.         0.13912167]
 [0.14980118 0.13912167 0.        ]]


In [29]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.3706637436963573, 1: 0.3618849304790072, 2: 0.2674513258246353}


In [30]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.3706637436963573, ['Künstliche', 'Intelligenz', '(KI)', 'bezieht', 'sich', 'auf', 'die', 'Fähigkeit', 'von', 'Maschinen', 'und', 'Computern,', 'Aufgaben', 'auszuführen,', 'die', 'normalerweise', 'menschliche', 'Intelligenz', 'erfordern']), (0.3618849304790072, ['Dazu', 'gehören', 'das', 'Lernen,', 'das', 'Problemlösen,', 'die', 'Spracherkennung', 'und', 'die', 'Entscheidungsfindung']), (0.2674513258246353, ['KI-Technologien', 'wie', 'maschinelles', 'Lernen', 'und', 'neuronale', 'Netze', 'werden', 'in', 'verschiedenen', 'Bereichen', 'eingesetzt,', 'von', 'autonomen', 'Fahrzeugen', 'und', 'Robotern', 'bis', 'hin', 'zu', 'personalisierten', 'Empfehlungssystemen', 'und', 'medizinischer', 'Diagnose.\n'])]


In [31]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  4


IndexError: list index out of range

In [ ]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

In [ ]:
file = open("5.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph

sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

In [ ]:
print("Sentences are ", sentences)

In [ ]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

In [ ]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)

In [ ]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

In [ ]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)

In [ ]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))

In [ ]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))